name: Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-nuget:
    name: Deployment

    runs-on: ubuntu-16.04

    steps:
    - name: Set version tag
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:11})

    - uses: actions/checkout@v1

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.101'

    - name: Overwrite files
      run: |
        sed 's/$(PackageVersion)/${{ steps.vars.outputs.tag }}/g' Obsessive.Defender/Obsessive.Defender.csproj > out.tmp
        cat out.tmp
        mv out.tmp Obsessive.Defender/Obsessive.Defender.csproj
        sed 's/$(PackageVersion)/${{ steps.vars.outputs.tag }}/g' Obsessive.Defender/build/Obsessive.Defender.props > out.tmp
        cat out.tmp
        mv out.tmp Obsessive.Defender/build/Obsessive.Defender.props

    - name: Build NuGet
      run: dotnet pack -c Release

    - name: Deploy NuGet
      run: dotnet nuget push Obsessive.Defender/bin/Release/Obsessive.Defender.${{ steps.vars.outputs.tag }}.nupkg -k ${{ secrets.CICD_KEY }} -s https://api.nuget.org/v3/index.json